// Skill → icon-slug lookup. Pure data + a resolver, deliberately NOT a
// "use client" module so it can be consumed by server components (JobCard,
// job detail page) without shipping this ~300-entry map to the browser.
// Client selectors that need it at runtime import it here too.

export const SKILL_ICONS: Record<string, string> = {
  /* Languages */
  "JavaScript":         "javascript",
  "TypeScript":         "typescript",
  "Python":             "python",
  "Go":                 "go",
  "Rust":               "rust",
  "Java":               "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg",
  "Kotlin":             "kotlin",
  "Swift":              "swift",
  "C++":                "cplusplus",
  "C#":                 "csharp",
  "PHP":                "php",
  "Ruby":               "ruby",
  "Scala":              "scala",
  "Elixir":             "elixir",
  "Dart":               "dart",
  "Groovy":             "apachegroovy",
  "Solidity":           "solidity",
  "R":                  "r",
  "MATLAB":             "mathworks",
  "Bash":               "gnubash",
  "Lua":                "lua",
  "Haskell":            "haskell",
  "Clojure":            "clojure",
  "HTML":               "html5",
  "CSS":                "css3",
  "Objective-C":        "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/objectivec/objectivec-plain.svg",
  "Perl":               "perl",
  "PowerShell":         "powershell",
  "Julia":              "julia",
  "Zig":                "zig",

  /* Frontend */
  "React":              "react",
  "React Native":       "react",
  "Next.js":            "nextdotjs",
  "Vue.js":             "vuedotjs",
  "Vue":                "vuedotjs",
  "Nuxt.js":            "nuxtdotjs",
  "Angular":            "angular",
  "Svelte":             "svelte",
  "SvelteKit":          "svelte",
  "Remix":              "remix",
  "Astro":              "astro",
  "Gatsby":             "gatsby",
  "Ember.js":           "emberdotjs",
  "Alpine.js":          "alpinedotjs",
  "Lit":                "lit",
  "Qwik":               "qwik",
  "Redux":              "redux",
  "Zustand":            "zustand",
  "MobX":               "mobx",
  "Three.js":           "threedotjs",
  "Tailwind CSS":       "tailwindcss",
  "Sass":               "sass",
  "SCSS/Sass":          "sass",
  "CSS Modules":        "css3",
  "styled-components":  "styledcomponents",
  "Emotion":            "styledcomponents",
  "Bootstrap":          "bootstrap",
  "Material UI":        "mui",
  "Chakra UI":          "chakraui",
  "Ant Design":         "antdesign",
  "Radix UI":           "radixui",
  "shadcn/ui":          "shadcnui",
  "Framer Motion":      "framer",
  "D3.js":              "d3dotjs",
  "Chart.js":           "chartdotjs",
  "WebGL":              "threedotjs",
  "Storybook":          "storybook",
  "Webpack":            "webpack",
  "Vite":               "vite",
  "esbuild":            "esbuild",
  "Turbopack":          "vercel",
  "Rollup":             "rollupjs",
  "Parcel":             "parcel",

  /* Backend / Frameworks */
  "Node.js":            "nodedotjs",
  "Express":            "express",
  "NestJS":             "nestjs",
  "Fastify":            "fastify",
  "Hono":               "hono",
  "Django":             "django",
  "FastAPI":            "fastapi",
  "Flask":              "flask",
  "Laravel":            "laravel",
  "Rails":              "rubyonrails",
  "Symfony":            "symfony",
  "Spring Boot":        "springboot",
  "Spring":             "spring",
  "Quarkus":            "quarkus",
  "Micronaut":          "micronaut",
  "Ktor":               "ktor",
  "Gin":                "go",
  "Echo":               "go",
  "Fiber":              "go",
  "Actix":              "rust",
  "Axum":               "rust",
  ".NET":               "dotnet",
  "GraphQL":            "graphql",
  "tRPC":               "trpc",
  "REST API":           "swagger",
  "gRPC":               "grpc",
  "WebSockets":         "socketdotio",
  "OpenAPI":            "openapiinitiative",
  "Bun":                "bun",
  "Deno":               "deno",

  /* Mobile */
  "Flutter":            "flutter",
  "Android":            "android",
  "iOS":                "apple",
  "Expo":               "expo",

  /* Databases */
  "PostgreSQL":         "postgresql",
  "MySQL":              "mysql",
  "SQLite":             "sqlite",
  "MariaDB":            "mariadb",
  "MongoDB":            "mongodb",
  "Redis":              "redis",
  "Elasticsearch":      "elasticsearch",
  "Cassandra":          "apachecassandra",
  "DynamoDB":           "amazondynamodb",
  "Firebase":           "firebase",
  "Firestore":          "googlefirebase",
  "Supabase":           "supabase",
  "Snowflake":          "snowflake",
  "BigQuery":           "googlebigquery",
  "Redshift":           "amazonredshift",
  "Prisma":             "prisma",
  "DrizzleORM":         "drizzle",
  "Drizzle ORM":        "drizzle",
  "SQLAlchemy":         "sqlalchemy",
  "Hibernate":          "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/hibernate/hibernate-original.svg",
  "TypeORM":            "typescript",
  "ClickHouse":         "clickhouse",
  "CockroachDB":        "cockroachlabs",
  "PlanetScale":        "planetscale",
  "Neon":               "neon",
  "Microsoft SQL Server": "microsoftsqlserver",
  "Oracle Database":    "oracle",
  "Neo4j":              "neo4j",
  "Couchbase":          "couchbase",
  "InfluxDB":           "influxdb",
  "Pandas":             "pandas",
  "pandas":             "pandas",
  "NumPy":              "numpy",
  "Jupyter":            "jupyter",

  /* Cloud */
  "Docker":             "docker",
  "Kubernetes":         "kubernetes",
  "AWS":                "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg",
  "Azure":              "microsoftazure",
  "GCP":                "googlecloud",
  "Vercel":             "vercel",
  "Netlify":            "netlify",
  "Cloudflare":         "cloudflare",
  "Railway":            "railway",
  "Fly.io":             "flyio",
  "DigitalOcean":       "digitalocean",
  "Heroku":             "heroku",

  /* DevOps */
  "Terraform":          "terraform",
  "Ansible":            "ansible",
  "Nginx":              "nginx",
  "Linux":              "linux",
  "Helm":               "helm",
  "ArgoCD":             "argo",
  "GitHub Actions":     "githubactions",
  "GitLab CI":          "gitlab",
  "CircleCI":           "circleci",
  "Jenkins":            "jenkins",
  "Bitbucket Pipelines": "bitbucket",

  /* Observability */
  "Prometheus":         "prometheus",
  "Grafana":            "grafana",
  "Datadog":            "datadog",
  "New Relic":          "newrelic",
  "Sentry":             "sentry",
  "OpenTelemetry":      "opentelemetry",

  /* Data / Streaming */
  "Kafka":              "apachekafka",
  "Spark":              "apachespark",
  "Apache Spark":       "apachespark",
  "Airflow":            "apacheairflow",
  "RabbitMQ":           "rabbitmq",
  "NATS":               "nats",
  "Redis Pub/Sub":      "redis",
  "SQS":                "amazonaws",
  "dbt":                "dbt",

  /* Build / Test */
  "Gradle":             "gradle",
  "Maven":              "apachemaven",
  "Selenium":           "selenium",
  "Cypress":            "cypress",
  "Jest":               "jest",
  "Playwright":         "playwright",
  "Mocha":              "mocha",
  "Testing Library":    "testinglibrary",
  "pytest":             "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pytest/pytest-original.svg",
  "JUnit":              "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/junit/junit-original.svg",
  "Swagger":            "swagger",
  "Vitest":             "vitest",
  "k6":                 "k6",

  /* Tools */
  "Figma":              "figma",
  "Git":                "git",
  "GitHub":             "github",
  "GitLab":             "gitlab",
  "Jira":               "jira",
  "Confluence":         "confluence",
  "Bitbucket":          "bitbucket",
  "Postman":            "postman",
  "Insomnia":           "insomnia",
  "OWASP":              "owasp",
  "Burp Suite":         "burpsuite",
  "Penetration Testing":"kalilinux",
  "SIEM":               "splunk",
  "Splunk":             "splunk",
  "Wireshark":          "wireshark",
  "Metasploit":         "metasploit",
  "Nessus":             "owasp",
  "Okta":               "okta",
  "CrowdStrike":        "owasp",
  "Zero Trust":         "owasp",
  "IAM":                "owasp",
  "PKI":                "owasp",
  "Vulnerability Management": "owasp",
  "Threat Modeling":    "owasp",
  "DevSecOps":          "owasp",
  "SAST":               "owasp",
  "DAST":               "owasp",
  "Cloud Security":     "owasp",
  "Network Security":   "owasp",
  "ISO 27001":          "owasp",
  "ISO 27701":          "owasp",
  "ISO 9001":           "owasp",
  "SOC 2":              "owasp",
  "PCI DSS":            "owasp",
  "GDPR":               "owasp",
  "HIPAA":              "owasp",
  "NIST Cybersecurity Framework": "owasp",
  "CISSP":              "owasp",
  "CISM":               "owasp",
  "CISA":               "owasp",
  "CEH":                "owasp",
  "CompTIA Security+":  "owasp",
  "OSCP":               "owasp",
  "CCSP":               "owasp",
  "VS Code":            "visualstudiocode",
  "Vim":                "vim",
  "IntelliJ":           "intellijidea",
  "Xcode":              "xcode",
  "Android Studio":     "androidstudio",

  /* Auth / Payments / Comms */
  "Auth0":              "auth0",
  "Clerk":              "clerk",
  "Stripe":             "stripe",
  "Twilio":             "twilio",
  "SendGrid":           "sendgrid",

  /* AI & ML */
  "Keras":              "keras",
  "MLflow":             "mlflow",
  "Matplotlib":         "matplotlib",
  "Plotly":             "plotly",
  "OpenCV":             "opencv",
  "spaCy":              "spacy",
  "Ollama":             "ollama",

  /* Design & Creative — Adobe suite */
  "Adobe Photoshop":    "adobephotoshop",
  "Adobe Illustrator":  "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/illustrator/illustrator-plain.svg",
  "Adobe InDesign":     "adobeindesign",
  "Adobe After Effects":"adobeaftereffects",
  "Adobe Premiere Pro": "adobepremierepro",
  "Adobe Lightroom":    "adobelightroom",
  "Adobe XD":           "adobexd",
  "Adobe Audition":     "adobeaudition",
  "Adobe Animate":      "adobeanimate",
  "Adobe Dimension":    "adobedimension",
  "Adobe Acrobat":      "adobeacrobat",
  "Adobe Dreamweaver":  "adobedreamweaver",

  /* Design & Creative — Affinity suite */
  "Affinity Designer":  "affinitydesigner",
  "Affinity Photo":     "affinityphoto",
  "Affinity Publisher": "affinitypublisher",

  /* Design & Creative — Other tools */
  "Canva":              "canva",
  "Sketch":             "sketch",
  "Framer":             "framer",
  "Webflow":            "webflow",
  "InVision":           "invision",
  "Zeplin":             "zeplin",
  "Marvel":             "marvelapp",

  /* 3D, Motion & Game */
  "Blender":            "blender",
  "Cinema 4D":          "cinema4d",
  "Unity":              "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/unity/unity-original.svg",
  "Unreal Engine":      "unrealengine",
  "DaVinci Resolve":    "davinciresolve",
  "Spline":             "figma",

  /* Marketing & Analytics */
  "Google Analytics":   "googleanalytics",
  "Google Ads":         "googleads",
  "HubSpot":            "hubspot",
  "Mailchimp":          "mailchimp",
  "Mixpanel":           "mixpanel",
  "Amplitude":          "amplitude",
  "Hotjar":             "hotjar",
  "WordPress":          "wordpress",
  "Shopify":            "shopify",
  "WooCommerce":        "woocommerce",
  "SEO":                "googlesearchconsole",
  "A/B Testing":        "googleanalytics",

  /* AI & ML */
  "TensorFlow":         "tensorflow",
  "PyTorch":            "pytorch",
  "Hugging Face":       "huggingface",
  "OpenAI API":         "openai",
  "LangChain":          "langchain",
  "scikit-learn":       "scikitlearn",

  /* Productivity & Collaboration */
  "Notion":             "notion",
  "Slack":              "slack",
  "Linear":             "linear",
  "Asana":              "asana",
  "Trello":             "trello",
  "Monday.com":         "mondaydotcom",
  "Microsoft Office":   "microsoftoffice",
  "Google Workspace":   "googleworkspace",

  /* Product & Methodology */
  "Agile/Scrum":        "jira",
  "Kanban":             "trello",
  "Product Management": "notion",
  "UX Research":        "figma",
};

/** Returns a full icon URL for a skill name, or null if no icon is available. */
export function getIconSrc(name: string): string | null {
  const entry = SKILL_ICONS[name];
  if (!entry) return null;
  if (entry.startsWith("https://")) return entry;
  return `https://cdn.simpleicons.org/${entry}`;
}
